# coding: utf-8

""" Project Euler problem #45. """

import math as mt


def problem():
    u""" Solve the problem.

    Triangle, pentagonal, and hexagonal numbers are generated by the
    following formulae:

    Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
    Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

    Answer: 1533776805

    """
    for n in range(144, 10**6):
        hexagonal = n * (2 * n - 1)
        pnum = (mt.sqrt(24 * hexagonal + 1) + 1) / 6
        if not pnum % 1:
            return hexagonal


if __name__ == '__main__':
    print problem()
